spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qiyue?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: qq.984515@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  file:
    path: log/qiyue.log
server:
  port: 8080
